RocketEnglish/RocketEnglishv2/Models/Lesson.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using Microsoft.Ajax.Utilities;
using RocketEnglishv2.DAO;

namespace RocketEnglishv2.Models
{
    public class Lesson
    {
        public int Id { get; set; }
        public int Level { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public List<Question> questions;

        public Lesson() : this(-1, -1, "No description", "Lesson name")
        {
        }

        public Lesson(int pId, int pLevel, string pDescription, string pName)
        {
            Id = pId;
            Level = pLevel;
            Description = pDescription;
            Name = pName;
            questions = new List<Question>();
        }

        public void pollQuestions()
        {
            RocketEnglish re = new RocketEnglish();

            List<PerguntaEscolhaMultipla> multipleChoiceQuestions = new List<PerguntaEscolhaMultipla>();
            List<PerguntaPalavra> fillQuestions = new List<PerguntaPalavra>();

            //polls questions from database
            multipleChoiceQuestions = re.PerguntaEscolhaMultipla
                .Where(b => b.idLicao == Id)
                .ToList();

            fillQuestions = re.PerguntaPalavra
                .Where(b => b.idLicao == Id)
                .ToList();


            //adds questions to questions List
            multipleChoiceQuestions.ForEach(delegate(PerguntaEscolhaMultipla pem)
            {
                questions.Add(new MultipleChoice(pem.id, pem.pergunta, pem.dica, "", pem.resposta, pem.imagem, pem.video, pem.errada1,
                    pem.errada2, pem.errada3));
            });

            fillQuestions.ForEach(delegate(PerguntaPalavra pp)
            {
                questions.Add(new Fill(pp.id, pp.pergunta, pp.dica, "", pp.resposta, pp.imagem, pp.video));
            });

            //randomize question order
            randomizeQuestions();
        }

        public void randomizeQuestions()
        {
            Random rnd = new Random();
            int ind1, ind2;
            int listSize = questions.Count;

            if (listSize <= 0)
            {
                throw new Exception("Lesson don't exist or don't has questions");
            }

            for (int i = 0; i < 5; i++)
            {
                ind1 = rnd.Next(listSize);

                do
                {
                    ind2 = rnd.Next(listSize);
                } while (ind1 == ind2);

                questionSwap(ind1, ind2);
            }
        }

        public void questionSwap(int ind1, int ind2)
        {
            Question tmpQ = questions[ind1];
            questions[ind1] = questions[ind2];
            questions[ind2] = tmpQ;
        }

        public List<Question> getWrongQuestions()
        {
            List<Question> wrongQuestions = new List<Question>();
            questions.ForEach(delegate(Question q)
            {
                if (!q.isCorrect())
                    wrongQuestions.Add(q);
            });
            return wrongQuestions;
        }

        public bool saveResults(int userId)
        {
            int correctCount = 0;
            bool isCompleted = false;

            RocketEnglish re = new RocketEnglish();

            foreach (Question q in questions)
            {
                correctCount += (q.isCorrect()) ? 1 : 0;

                if (q.GetType() == typeof (MultipleChoice))
                    processMCQ(re,q,userId);
                else
                    processFQ(re,q,userId);


            }

            isCompleted = (correctCount > 6) ? true : false;

            if (isCompleted)
            {
                re.Utilizador.Find(userId)
                  .Licao
                  .Add(re.Licao.Find(Id));
            }

            re.SaveChanges();

            return isCompleted;
        }

        private void processMCQ(RocketEnglish re, Question q, int userId)
        {
            UtilizadorPerguntaEscolhaMultipla upem = re.UtilizadorPerguntaEscolhaMultipla.Find(q.ID, userId);
            if (upem == null)
            {
                upem = new UtilizadorPerguntaEscolhaMultipla();
                upem.idPerguntaEscolhaMultipla = q.ID;
                upem.idUtilizador = userId;
                upem.correta = q.isCorrect();
                re.UtilizadorPerguntaEscolhaMultipla.Add(upem);
            }
            else
            {
                upem.correta = q.isCorrect();
                re.Entry(upem).CurrentValues.SetValues(upem);
            }

        }

        public void processFQ(RocketEnglish re, Question q, int userId)
        {
            UtilizadorPerguntaPalavra upp = re.UtilizadorPerguntaPalavra.Find(q.ID, userId);
            if (upp == null)
            {
                upp = new UtilizadorPerguntaPalavra();
                upp.idPerguntaPalavra = q.ID;
                upp.idUtilizador = userId;
                upp.correta = q.isCorrect();
                re.UtilizadorPerguntaPalavra.Add(upp);
            }
            else
            {
                upp.correta = q.isCorrect();
                re.Entry(upp).CurrentValues.SetValues(upp);   
            }
        }
    }
}

RocketEnglish/RocketEnglishv2/Models/Question.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RocketEnglishv2.Models
{
    public abstract class Question
    {
        public int ID { get; set; }
        public string Text { get; set; }
        public string Tip { get; set; }
        public string Answer { get; set; }
        public string Correct { get; set; }
        public string Image { get; set; }
        public string Video { get; set; }

        public Question() : this(0, "", "", "", "", "", "") { }
        public Question(int pId, string pText, string pTip, string pAnswer, string pCorrect) : this(pId, pText, pTip, pAnswer, pCorrect, "", "") { }
        public Question(Question q) : this(q.ID, q.Text, q.Tip, q.Answer, q.Correct, "", "") { }
        public Question(int pId, string pText, string pTip, string pAnswer, string pCorrect, string pImage, string pVideo)
        {
            ID = pId;
            Text = pText;
            Tip = pTip;
            Answer = pAnswer;
            Correct = pCorrect;
            Image = pImage;
            Video = pVideo;
        }

        public bool isCorrect()
        {
            return Answer.Equals(Correct, StringComparison.Ordinal);
        }

        public void answer(string a)
        {
            Answer = a;
        }
    }


}

RocketEnglish/RocketEnglishv2/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RocketEnglishv2.Models;
using System.IO;
using System.Web.Script.Serialization;

namespace RocketEnglishv2.Controllers
{
    public class QuestionController : Controller
    {
        // GET: Question
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Answer(int id)
        {
            readLoadArgs();
            
            StreamReader sr = new StreamReader(Request.InputStream);

            JavaScriptSerializer js = new JavaScriptSerializer();
            dynamic answerJson = js.Deserialize<dynamic>(sr.ReadLine());
            string answer = answerJson["answer"];

            Question q = ViewBag.Challenge.questions[ViewBag.NumQuestion];
            Object ret;
            if (q.Answer == "" || !(ViewBag.Challenge is Lesson) )
            {
                q.answer(answer);
                if (ViewBag.Challenge is Lesson)
                {
                    ret = new { isCorrect = q.isCorrect() };
                }
                else
                {
                    ret = new { };
                }
            }
            else
            {
                ret = new { error = "anwsered", anwser = q.Answer};
            }
           
            

            return Json(ret, JsonRequestBehavior.AllowGet); ;
        }

        public ActionResult Test(int id)
        {
            readLoadArgs();

            if (!(ViewBag.Challenge is CategoryTest))
            { throw new Exception("Error this token is not from a CategoryTest, do introduction first"); }

            CategoryTest l = ViewBag.Challenge as CategoryTest;

            ViewBag.Action = "Test";
            ViewBag.id = l.CategoryLevel.Level;
            return View("Lesson",l.questions);
        }

        public ActionResult Global(int id)
        {
            readLoadArgs();

            if (!(ViewBag.Challenge is GlobalTest))
            { throw new Exception("Error this token is not from a GlobalTest, do introduction first"); }

            GlobalTest l = ViewBag.Challenge as GlobalTest;

            ViewBag.Action = "Global";
            ViewBag.id = l.Level;
            return View("Lesson", l.questions);
        }

        public ActionResult Lesson(int id)
        {
            readLoadArgs();

            if (!(ViewBag.Challenge is Lesson))
            { throw new Exception("Error this token is not from a Lesson, do introduction first"); }

            Lesson l = ViewBag.Challenge as Lesson;

            ViewBag.Action = "Lesson";
            ViewBag.id = l.Id;
            return View(l.questions);
        }

        private void readLoadArgs()
        {
            sessionUser();
            String token = Request.QueryString["token"];
            if (token == null) 
            { throw new Exception("Error no available token - do Introduction first"); }

            String strNQuestion = Request.QueryString["NumQuestion"];
            int numQuestion = (strNQuestion == null) ? 0 : Convert.ToInt32(strNQuestion);

            HttpContext context = System.Web.HttpContext.Current;
            if (context.Session[token] == null)
            { throw new Exception("Error wrong token, do introduction first"); }

            ViewBag.NumQuestion = numQuestion;
            ViewBag.Token = token;
            dynamic v = context.Session[token];
            ViewBag.Challenge = v.challenge;
        }
        
        public Models.User sessionUser()
        {
            HttpContext context = System.Web.HttpContext.Current;
            if (context.Session["user"] == null || !(context.Session["user"] is Models.User))
            {
                throw new Exception("Do login first");
            }
            ViewBag.User = context.Session["user"];
            return context.Session["user"] as Models.User;
        }
    }
}

RocketEnglish/RocketEnglishv2/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using RocketEnglishv2.DAO;
using RocketEnglishv2.Services;
using RocketEnglishv2.Models;
using System.IO;


namespace RocketEnglishv2.Controllers
{




    public class TestController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            RocketEnglish a = new RocketEnglish();
            Categoria c = a.Categoria
                .Where(b => b.id == 1)
                .First();
            Debug.WriteLine("Categoria" + c.ToString());


            return View();
        }

        public ActionResult CleanDB()
        {
            string s = Server.MapPath("~/Content/");
            InstallService install = new InstallService(s);

            install.DBClean();

            return View("Debug");
        }

        // GET: Test
        public ActionResult Init()
        {
            string s = Server.MapPath("~/Content/");
            InstallService install = new InstallService(s);

            install.DBClean();

            //DBexpander dbe = new DBexpander();
            //dbe.processFile(s+"csv/example.csv");

            install.DBLoadSample();

            return View();
        }

        public ActionResult Init2()
        {
            string s = Server.MapPath("~/Content/");
            InstallService install = new InstallService(s);

            //install.DBClean();

            //DBexpander dbe = new DBexpander();
            //dbe.processFile(s+"csv/example.csv");

            //install.DBLoadSample();
            install.UserDoLessons();

            return View("init");
        }

        // GET: Test
        public ActionResult Model()
        {
           
            //Lesson l = new Lesson(1, "Descricao", "A tua prima");
            //l.pollQuestions();

            //GlobalTest cg = new GlobalTest(1);
            //cg.pollQuestions();

            //CategoryLevel cl = new CategoryLevel(1, "a tua prima", 1, 0);
            //CategoryTest ct = cl.CreateCategoryTest();
            
            return View("Debug");
        }
        
        public ActionResult Home()
        {
            RocketEnglishv2.DAO.RocketEnglish a = new RocketEnglish();
            Utilizador u = a.Utilizador.First();

            RocketEnglishv2.Models.User user = new Models.User(u.id, u.nome, u.username, u.email, u.passsword, u.nivelGlobal, u.loginSeguidosMaximo, u.loginSeguidosAtual, u.dataUltimoLogin, u.tutorialFeito);

            HttpContext context = System.Web.HttpContext.Current;
            context.Session["user"] = user;

            return RedirectToAction("Index", "Home");
        }


        public ActionResult Video()
        {

            return View("Debug");
        }
        
        public ActionResult Image()
        {
            return View("Debug");
        }

        public ActionResult TestSave()
        {

            return View("Debug");
        }

        public ActionResult Translator()
        {
            String word = TranslatorContainer.TranslateBing("Bus", "en", "pt-pt");
            return View("Debug");
        }
    }
}

RocketEnglish/RocketEnglishv2/Views/Question/Global.cshtml
@using RocketEnglishv2.Models;
@model GlobalTest

RocketEnglish/RocketEnglishv2/Views/Question/Lesson.cshtml
@using Microsoft.Web.Helpers;
@using RocketEnglishv2.Models;
@model List<Question>
@{
    Question question = null;
    if (ViewBag.NumQuestion < Model.Count && ViewBag.NumQuestion >= 0)
    {
        question = Model[ViewBag.NumQuestion];
    }
    String joke = "put here one joke";
}
<div class="container">
    <div class="row">
        <div class="question-wrapper">
            <div id="user-progress"></div>
            <div class="question-media">
                @if (question.Image != null && question.Image != "none" && question.Image != "")
                {
                    <img src="@Url.Content(question.Image)" />
                }
                
                @if (question.Video != null && question.Video != "none" && question.Video != "")
                {
                    @Video.Flash(
                    path: question.Video,
                    width: "600",
                    height: "350");
                    //  autoStart: true,
                    //    playCount: 2,
                    //   uiMode: "full",
                    //stretchToFit: true,
                    // enableContextMenu: true,
                    //mute: false,
                    //volume: 75)
                }
            </div>
            <div class="question-text-wrapper">
                <p class="question-text">@question.Text</p>
            </div>
            <div class="answer-wrapper">
                <form id="answerForm" data-tip="@question.Tip" data-request-url="@Url.Action("Answer", new { @id = ViewBag.Id, @numQuestion = ViewBag.NumQuestion, @token = ViewBag.Token })">
                    <!-- HERE GOES Question DATA -->
                    @if (question is MultipleChoice)
                    {

                        @Html.Partial("_QuestionMultipleChoice", (MultipleChoice)question)
                    }
                    @if (question is Fill)
                    {
                        @Html.Partial("_QuestionFill", (Fill)question)
                    }
                    <input type="submit" style="position: absolute; left: -9999px" />
                </form>


            </div>
            @if (ViewBag.NumQuestion > 0)
            {
                    <a href="@Url.Action((string)ViewBag.Action, "Question",
                    new { @id = ViewBag.Id, @numQuestion = ViewBag.NumQuestion - 1, @token = ViewBag.Token })"
                    class="arrow arrow-right" id="button-prev"><span>&#9668;&#9668;</span></a>
            }
            <!-- next -->
            @if (ViewBag.NumQuestion < Model.Count - 1)
            {
                <a href="@Url.Action((string)ViewBag.Action, "Question",
                    new { @id = ViewBag.Id, @numQuestion = ViewBag.NumQuestion + 1, @token = ViewBag.Token })"
                    class="arrow arrow-left" id="button-next"><span>&#9658;&#9658;</span></a>
            }
            else
            {
                <a href="@Url.Action((string)ViewBag.Action, "review",
                    new { @id = ViewBag.Id, @token = ViewBag.Token })" class="arrow arrow-left" id="button-next"><span>&#9658;&#9658;</span></a>
            }
            <!-- usar as merdas que eu tinha criado para os botoes dava geito...  -->
            <!-- <a href="#" class="arrow arrow-right" id="button-prev"><span>&#9668;&#9668;</span></a>-->
            <!-- <a href="#" class="arrow arrow-left" id="button-next"><span>&#9658;&#9658;</span></a>-->
        </div>
    </div>
</div>

    <script language="javascript">
        // TODO: MODIFY This request to use a restfull API
        // ALSO MODIFY to do this on .next in Lesson.cshtml

        RocketEnglish.init.push(function () {

            var registerAnwser = function () {
                var radio = $('input[name=answer]:checked', '#answerForm').val();
                var input = $('input[name=answer]', '#answerForm').val();
                var answerValue = (radio !== undefined) ? radio : input;
                var url = $('#answerForm').data('request-url');
                $.ajax({
                    type: 'POST',
                    url: url,
                    dataType: 'json',
                    data: JSON.stringify({ answer: answerValue }),
                    success: function (data) {
                        if (data.isCorrect === true) {
                            RocketEnglish.SimpleInteraction("You are correct!!");
                            makeHappy();
                        } else if (data.isCorrect === false) {
                            makeSad();
                            RocketEnglish.SimpleInteraction("Wrong answer...");
                        } else if (data.error === 'anwsered') {
                            $("input[name=answer]", '#answerForm').val(data.anwser);
                        }
                    },
                    error: function (err) {
                        console.log(err);
                    }
                });
            }

            //$('#button-next').click(registerAnwser);
            //$('#button-end').click(registerAnwser);
            //$('#button-prev').click(registerAnwser);
            //$('#action-button').click(registerAnwser);

            $("input[name=answer]", '#answerForm').change(function () {
                registerAnwser();
            });

            $('#answerForm').submit(function (event) {
                registerAnwser();
                //window.location.href = $('#button-next').attr('href');
                event.preventDefault();
            });

            var inte = RocketEnglish.Avatar.interactionsAll;
            @if (ViewBag.Action == "Lesson")
            {
                <text> 
            inte.tip.tip = $('#answerForm').data('tip');
            RocketEnglish.Avatar.interactionsActual.tip = inte.tip;

                </text> 
            }
            inte.joke.joke = "@joke";
            RocketEnglish.Avatar.interactionsActual.joke = inte.joke;
        });
    </script>

RocketEnglish/RocketEnglishv2/Views/Question/Test.cshtml
@using RocketEnglishv2.Models;
@model CategoryTest

RocketEnglish/RocketEnglishv2/Views/Question/_QuestionFill.cshtml
@using RocketEnglishv2.Models;
@model Fill

    <input type="text" name="answer" id="answer" placeholder="Answer" value="@Model.Answer" />

<script>
    // TODO: MODIFY This request to use a restfull API
    // ALSO MODIFY to do this on .next in Lesson.cshtml
   // $(function () {
   //     $('.link').click(function () {
   //         var ipvalue = $("#answer").val();
   //         this.href = this.href.replace("xxx", ipvalue);
  //      });
  //  });
</script>

<script>
    $(document).ready(function () {
        $(":radio").labelauty();
        $(".to-labelauty-icon").labelauty({ label: false });
    });
</script>

RocketEnglish/RocketEnglishv2/Views/Question/_QuestionMultipleChoice.cshtml
@using RocketEnglishv2.Models;
@using RocketEnglishv2.Services;

@model MultipleChoice

        @foreach (string str in Utils.shuffle(@Model.All))
        {
            string check = Model.Answer.Equals(str) ? "checked" : "";

            <input type="radio" name="answer" data-labelauty="@str" class="to-labelauty-icon" value="@str" @check />
        }

<script>

    $(document).ready(function(){
        $(".to-labelauty-icon").labelauty();
    });
</script>