RocketEnglish/RocketEnglishv2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RocketEnglishv2.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Web.Script.Serialization;
using RocketEnglishv2.Services;

namespace RocketEnglishv2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            User u = sessionUser();
            u.loadCategories();
            var e = u.Categories.GetEnumerator();
            e.MoveNext();

//            List<List<CategoryLevel>> categorys = CategoryLevel.findAll();
            ViewBag.User = u;
            ViewBag.Categories = u.Categories;
            ViewBag.GlobalLvl = u.GlobalLvl;
            ViewBag.NewGlobalLvlAvaliable = true;
            foreach(List<CategoryLevel> l in u.Categories.Values){
                ViewBag.NewGlobalLvlAvaliable = ViewBag.NewGlobalLvlAvaliable
                    && l[u.GlobalLvl + 1].IsDone();
            }
            

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public Models.User sessionUser()
        {
            HttpContext context = System.Web.HttpContext.Current;
            if (context.Session["user"] == null || !(context.Session["user"] is Models.User))
            {
                throw new Exception("Do login first");
            }
            return context.Session["user"] as Models.User;
        }
    }
}

RocketEnglish/RocketEnglishv2/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using RocketEnglishv2.DAO;
using RocketEnglishv2.Services;
using RocketEnglishv2.Models;
using System.IO;


namespace RocketEnglishv2.Controllers
{




    public class TestController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            RocketEnglish a = new RocketEnglish();
            Categoria c = a.Categoria
                .Where(b => b.id == 1)
                .First();
            Debug.WriteLine("Categoria" + c.ToString());


            return View();
        }

        public ActionResult CleanDB()
        {
            string s = Server.MapPath("~/Content/");
            InstallService install = new InstallService(s);

            install.DBClean();

            return View("Debug");
        }

        // GET: Test
        public ActionResult Init()
        {
            string s = Server.MapPath("~/Content/");
            InstallService install = new InstallService(s);

            install.DBClean();

            //DBexpander dbe = new DBexpander();
            //dbe.processFile(s+"csv/example.csv");

            install.DBLoadSample();

            return View();
        }

        public ActionResult Init2()
        {
            string s = Server.MapPath("~/Content/");
            InstallService install = new InstallService(s);

            //install.DBClean();

            //DBexpander dbe = new DBexpander();
            //dbe.processFile(s+"csv/example.csv");

            //install.DBLoadSample();
            install.UserDoLessons();

            return View("init");
        }

        // GET: Test
        public ActionResult Model()
        {
           
            //Lesson l = new Lesson(1, "Descricao", "A tua prima");
            //l.pollQuestions();

            //GlobalTest cg = new GlobalTest(1);
            //cg.pollQuestions();

            //CategoryLevel cl = new CategoryLevel(1, "a tua prima", 1, 0);
            //CategoryTest ct = cl.CreateCategoryTest();
            
            return View("Debug");
        }
        
        public ActionResult Home()
        {
            RocketEnglishv2.DAO.RocketEnglish a = new RocketEnglish();
            Utilizador u = a.Utilizador.First();

            RocketEnglishv2.Models.User user = new Models.User(u.id, u.nome, u.username, u.email, u.passsword, u.nivelGlobal, u.loginSeguidosMaximo, u.loginSeguidosAtual, u.dataUltimoLogin, u.tutorialFeito);

            HttpContext context = System.Web.HttpContext.Current;
            context.Session["user"] = user;

            return RedirectToAction("Index", "Home");
        }


        public ActionResult Video()
        {

            return View("Debug");
        }
        
        public ActionResult Image()
        {
            return View("Debug");
        }

        public ActionResult TestSave()
        {

            return View("Debug");
        }

        public ActionResult Translator()
        {
            String word = TranslatorContainer.TranslateBing("Bus", "en", "pt-pt");
            return View("Debug");
        }
    }
}

RocketEnglish/RocketEnglishv2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

RocketEnglish/RocketEnglishv2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RocketEnglish/RocketEnglishv2/Views/Home/Index.cshtml
@using RocketEnglishv2.Models;

<div class="container" id="main-menu-container">
    <div class="row main-menu-wrapper">
        @foreach (List<CategoryLevel> l in ViewBag.Categories.Values)
        { 
             @Html.Partial("_Category", l)
        }
     </div>
   <div class="row main-menu-wrapper" id="main-level-wrapper">
        <div class="col-xs-3 main-category-label">
            <p>Level</p>
        </div>
        <div class="col-xs-9">
            <div class="main-category-wrapper">
                <div class="main-category-content">
                    @{
                        float step = 20.0f;
                        float currentStep = step;
                    }
                    
                    <div class="checkpoint">0</div>
                    @for (int lvl = 0; lvl < 5; lvl++)
                    {
                        <div class="checkpoint" style="left: @currentStep.ToString().Replace(",", ".")%">
                            @Html.ActionLink("" + (lvl + 1), "Global", "Introduction", new { id = lvl + 1}, null) 
                        </div>
                        currentStep += step;
                    }

                </div>
                @{
                    var globalPercent = (ViewBag.GlobalLvl -1) * (step + 3);
                }

                <div class="progress" style="width: @globalPercent.ToString().Replace(",", ".")%">
                    <div class="main-category-content" id="main-level-content">
                        <div class="checkpoint">
                            <a href="">0</a>
                        </div>
                        @{ currentStep = step; }
                        @for (int lvl = 0; lvl < 5; lvl++)
                        {
                            <div class="checkpoint" style="left: @currentStep.ToString().Replace(",", ".")%">
                                @Html.ActionLink("" + (lvl + 1), "Global", "Introduction", new { id = lvl + 1}, null)
                            </div>
                            currentStep += step;
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end of progress bars -->

    <script>
        RocketEnglish.init.push(function () {
            var registerUnlockable = function () {
                var value = "something goes here";
                var url = $('#answerForm').data('request-url');
                $.ajax({
                    type: 'POST',
                    url: url,
                    dataType: 'json',
                    data: JSON.stringify({ answer: answerValue }),
                    success: function (data) {
                        if (data.isCorrect === true) {
                            alert("You are correct!");
                            //heyy is correct
                        } else if (data.isCorrect === false) {
                            alert("Wrong answer...");
                        } else {
                            // do nothing..
                        }
                    },
                    error: function (err) {
                        console.log(err);
                    }
                });
            }



            var inte = RocketEnglish.Avatar.interactionsAll;
            RocketEnglish.Avatar.interactionsActual.joke = inte.joke;
            RocketEnglish.Avatar.interactionsActual.translate = inte.translate;
        });
    </script>
</div>

RocketEnglish/RocketEnglishv2/Views/Home/_Category.cshtml
@using RocketEnglishv2.Models;
@model List<CategoryLevel>


@if (Model.Count > 0)
{
    <div class="row main-menu-wrapper">
        <div class="col-xs-3 main-category-label">
            <p>@Model[0].Name</p> <!-- category name -->
        </div>
        <div class="col-xs-9">
            <div class="main-category-wrapper">
                <div class="main-category-content">
                    <div class="checkpoint"><a href="">0</a></div>
                    @{
                        var completeSteps = 0;
                        var testCount = 0;

                        float step = 6.66f;
                        float lessonCount = step;
                     }
                    @foreach (CategoryLevel cl in Model)
                    {
                          var available = "disabled";
                          if(cl.IsAvailable())
                            { available = ""; }
                          if(cl.IsDone())
                            { completeSteps += 1; }


                       foreach (LessonInfo l in cl.LessonInfos.Values)
                       {
                            <span class="lesson" style="left: @lessonCount.ToString().Replace(",", ".")%">
                                <!--<a href="">&bull;</a>-->
                                @if(l.IsAvailable())
                                { @Html.ActionLink("•", "Lesson", "Introduction", new { id = cl.Level, idLesson = l.Id, idCategory = cl.CategoryId }, null);
                                }
                                @if (l.IsDone())
                                { completeSteps += 1;  }
                            </span>
                            lessonCount+= step;
                        }
                        <div class="checkpoint" style="left: @lessonCount.ToString().Replace(",", ".")%">
                            @{ testCount++; }
                            @if(cl.IsAvailable())
                            { @Html.ActionLink(cl.Level + "", "Test", "Introduction", new { id = cl.Level, idCategory = cl.CategoryId }, null); }
                            else
                            { @Html.ActionLink(cl.Level + "", "Test", "Introduction", new { id = cl.Level, idCategory = cl.CategoryId }, new { @class="disabled"}); }
                        </div>
                        lessonCount+= step;
                    }
                    @{
                        var percent = completeSteps * (step + 1);
                        lessonCount = step;
                    }
                    <div class="progress" style="width: @percent.ToString().Replace(",",".")%">
                    <!--<div class="progress" style="width: 50%">-->

                    <div class="main-category-content">
                    <div class="checkpoint"><a href="">0</a></div>
                        @foreach (CategoryLevel cl in Model)
                        {
                            foreach (LessonInfo l in cl.LessonInfos.Values)
                            {
                                <span class="lesson" style="left: @lessonCount.ToString().Replace(",", ".")%">
                                    <!--<a href="">&bull;</a>-->
                                    @Html.ActionLink("•", "Lesson", "Introduction", new { id = cl.Level, idLesson = l.Id, idCategory = cl.CategoryId }, null)
                                </span>
                                    lessonCount += step;
                            }
                            <div class="checkpoint" style="left: @lessonCount.ToString().Replace(",", ".")%">
                                @Html.ActionLink(cl.Level + "", "Test", "Introduction", new { id = cl.Level, idCategory = cl.CategoryId }, null)
                            </div>
                                lessonCount += step;
                        }
                    </div>
                   </div>
                </div>
           </div>
        </div>
    </div>
}