RocketEnglish/RocketEnglishv2/Models/Lesson.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using Microsoft.Ajax.Utilities;
using RocketEnglishv2.DAO;

namespace RocketEnglishv2.Models
{
    public class Lesson
    {
        public int Id { get; set; }
        public int Level { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public List<Question> questions;

        public Lesson() : this(-1, -1, "No description", "Lesson name")
        {
        }

        public Lesson(int pId, int pLevel, string pDescription, string pName)
        {
            Id = pId;
            Level = pLevel;
            Description = pDescription;
            Name = pName;
            questions = new List<Question>();
        }

        public void pollQuestions()
        {
            RocketEnglish re = new RocketEnglish();

            List<PerguntaEscolhaMultipla> multipleChoiceQuestions = new List<PerguntaEscolhaMultipla>();
            List<PerguntaPalavra> fillQuestions = new List<PerguntaPalavra>();

            //polls questions from database
            multipleChoiceQuestions = re.PerguntaEscolhaMultipla
                .Where(b => b.idLicao == Id)
                .ToList();

            fillQuestions = re.PerguntaPalavra
                .Where(b => b.idLicao == Id)
                .ToList();


            //adds questions to questions List
            multipleChoiceQuestions.ForEach(delegate(PerguntaEscolhaMultipla pem)
            {
                questions.Add(new MultipleChoice(pem.id, pem.pergunta, pem.dica, "", pem.resposta, pem.imagem, pem.video, pem.errada1,
                    pem.errada2, pem.errada3));
            });

            fillQuestions.ForEach(delegate(PerguntaPalavra pp)
            {
                questions.Add(new Fill(pp.id, pp.pergunta, pp.dica, "", pp.resposta, pp.imagem, pp.video));
            });

            //randomize question order
            randomizeQuestions();
        }

        public void randomizeQuestions()
        {
            Random rnd = new Random();
            int ind1, ind2;
            int listSize = questions.Count;

            if (listSize <= 0)
            {
                throw new Exception("Lesson don't exist or don't has questions");
            }

            for (int i = 0; i < 5; i++)
            {
                ind1 = rnd.Next(listSize);

                do
                {
                    ind2 = rnd.Next(listSize);
                } while (ind1 == ind2);

                questionSwap(ind1, ind2);
            }
        }

        public void questionSwap(int ind1, int ind2)
        {
            Question tmpQ = questions[ind1];
            questions[ind1] = questions[ind2];
            questions[ind2] = tmpQ;
        }

        public List<Question> getWrongQuestions()
        {
            List<Question> wrongQuestions = new List<Question>();
            questions.ForEach(delegate(Question q)
            {
                if (!q.isCorrect())
                    wrongQuestions.Add(q);
            });
            return wrongQuestions;
        }

        public bool saveResults(int userId)
        {
            int correctCount = 0;
            bool isCompleted = false;

            RocketEnglish re = new RocketEnglish();

            foreach (Question q in questions)
            {
                correctCount += (q.isCorrect()) ? 1 : 0;

                if (q.GetType() == typeof (MultipleChoice))
                    processMCQ(re,q,userId);
                else
                    processFQ(re,q,userId);


            }

            isCompleted = (correctCount > 6) ? true : false;

            if (isCompleted)
            {
                re.Utilizador.Find(userId)
                  .Licao
                  .Add(re.Licao.Find(Id));
            }

            re.SaveChanges();

            return isCompleted;
        }

        private void processMCQ(RocketEnglish re, Question q, int userId)
        {
            UtilizadorPerguntaEscolhaMultipla upem = re.UtilizadorPerguntaEscolhaMultipla.Find(q.ID, userId);
            if (upem == null)
            {
                upem = new UtilizadorPerguntaEscolhaMultipla();
                upem.idPerguntaEscolhaMultipla = q.ID;
                upem.idUtilizador = userId;
                upem.correta = q.isCorrect();
                re.UtilizadorPerguntaEscolhaMultipla.Add(upem);
            }
            else
            {
                upem.correta = q.isCorrect();
                re.Entry(upem).CurrentValues.SetValues(upem);
            }

        }

        public void processFQ(RocketEnglish re, Question q, int userId)
        {
            UtilizadorPerguntaPalavra upp = re.UtilizadorPerguntaPalavra.Find(q.ID, userId);
            if (upp == null)
            {
                upp = new UtilizadorPerguntaPalavra();
                upp.idPerguntaPalavra = q.ID;
                upp.idUtilizador = userId;
                upp.correta = q.isCorrect();
                re.UtilizadorPerguntaPalavra.Add(upp);
            }
            else
            {
                upp.correta = q.isCorrect();
                re.Entry(upp).CurrentValues.SetValues(upp);   
            }
        }
    }
}

RocketEnglish/RocketEnglishv2/Controllers/IntroductionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RocketEnglishv2.Models;

namespace RocketEnglishv2.Controllers
{
    public class IntroductionController : Controller
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="nivel"></param>
        // GET: Introduction/Test/5
        public ActionResult Test(int id)
        {
            User u = sessionUser();
            // get arguments
            String strIdCategory = Request.QueryString["idCategory"];
            if (strIdCategory == null)
            {
                // error
            }
            int idCategory = Convert.ToInt32(strIdCategory);
            string token = getNewToken();

            // contruct objects
            CategoryLevel cl = u.Categories[idCategory].ElementAt(id);
            CategoryTest ct = cl.CreateCategoryTest();
            
            // save in session Objects
            HttpContext context = System.Web.HttpContext.Current;
            context.Session[token] = new { challenge = ct, CategoryLevel = cl };

            // view
            ViewBag.token = token;
            ViewBag.level = id;
            return View(ct);
        }

        public ActionResult Global(int id)
        {
            string token = getNewToken();
            User u = sessionUser();

            GlobalTest ct = new GlobalTest(id);
            ct.pollQuestions();

            // save in session Objects
            HttpContext context = System.Web.HttpContext.Current;
            context.Session[token] = new { challenge = ct };

            ViewBag.token = token;
            ViewBag.nivel = id;
            return View(ct);
        }

        public ActionResult Lesson(int id)
        {
            int level = id;
            User u = sessionUser();
            string token = getNewToken();
            String strIdCategory = Request.QueryString["idCategory"];
            if (strIdCategory == null) throw new Exception("Wrong Url, must have idCategory");
            int idCategory = Convert.ToInt32(strIdCategory);
            String strIdLesson = Request.QueryString["idLesson"];
            if (strIdLesson == null) throw new Exception("Wrong Url, must have idLesson");
            int idLesson = Convert.ToInt32(strIdLesson);

            CategoryLevel cl = u.Categories[idCategory].ElementAt(level - 1);
            Lesson l = cl.LessonInfos[idLesson].fetchLesson();

            // save in session Objects
            HttpContext context = System.Web.HttpContext.Current;
            context.Session[token] = new { challenge = l, CategoryLevel = cl };

            ViewBag.token = token;
            ViewBag.nivel = id;
            return View(l);
        }

        private string getNewToken()
        {
            var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            var random = new Random();
            return new string(
                Enumerable.Repeat(chars, 8)
                          .Select(s => s[random.Next(s.Length)])
                          .ToArray());
        }

        public Models.User sessionUser()
        {
            HttpContext context = System.Web.HttpContext.Current;
            if (context.Session["user"] == null || !(context.Session["user"] is Models.User))
            {
                throw new Exception("Do login first");
            }
            ViewBag.User = context.Session["user"];
            return context.Session["user"] as Models.User;
        }
    }
}

RocketEnglish/RocketEnglishv2/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RocketEnglishv2.DAO;
using RocketEnglishv2.Models;

namespace RocketEnglishv2.Controllers
{
    public class ReviewController : Controller
    {
        // GET: Review
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Global(int id)
        {
            readLoadArgs();

            if (!(ViewBag.Challenge is GlobalTest))
            { throw new Exception("Error this token is not from a GlobalTest, do introduction first"); }

            GlobalTest gt = ViewBag.Challenge as GlobalTest;

            //check bool to inform user
            bool isCompleted = gt.saveGlobalTestResults(sessionUser().Id);
            if (isCompleted)
            {
                ((User)ViewBag.User).GlobalLvl += (((User)ViewBag.User).GlobalLvl < gt.Level + 1) ? 1:0;
            }

            ViewBag.id = gt.Level;

            return View(gt);
        }
        
        public ActionResult Test(int id)
        {
            readLoadArgs();

            if (!(ViewBag.Challenge is CategoryTest))
            { throw new Exception("Error this token is not from a CategoryTest, do introduction first"); }

            CategoryTest ct = ViewBag.Challenge as CategoryTest;

            //check bool to inform user
            bool isCompleted = ct.saveCategoryTestResults(sessionUser().Id);

            ViewBag.id = ct.CategoryLevel.Level;
            return View(ct);
        }

        public ActionResult Lesson(int id)
        {
            readLoadArgs();

            if (!(ViewBag.Challenge is Lesson))
            { throw new Exception("Error this token is not from a Lesson, do introduction first"); }

            Lesson l = ViewBag.Challenge as Lesson;

            //check bool to inform user
            bool isCompleted = l.saveResults(sessionUser().Id);

            ViewBag.id = l.Id;
            return View(l);
        }

        private void readLoadArgs()
        {
            String token = Request.QueryString["token"];
            if (token == null)
            { throw new Exception("Error no available token - do Introduction first"); }

            HttpContext context = System.Web.HttpContext.Current;
            if (context.Session[token] == null)
            { throw new Exception("Error wrong token, do introduction first"); }

            ViewBag.Token = token;
            dynamic v = context.Session[token];
            ViewBag.Challenge = v.challenge;
            if (v.GetType().GetProperty("CategoryLevel") != null)
            {
                ViewBag.CategoryLevel = v.CategoryLevel;
            }
        }

        public Models.User sessionUser()
        {
            HttpContext context = System.Web.HttpContext.Current;
            if (context.Session["user"] == null || !(context.Session["user"] is Models.User))
            {
                throw new Exception("Do login first");
            }
            ViewBag.User = context.Session["user"];
            return context.Session["user"] as Models.User;
        }
    }
}

RocketEnglish/RocketEnglishv2/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using RocketEnglishv2.DAO;
using RocketEnglishv2.Services;
using RocketEnglishv2.Models;
using System.IO;


namespace RocketEnglishv2.Controllers
{




    public class TestController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            RocketEnglish a = new RocketEnglish();
            Categoria c = a.Categoria
                .Where(b => b.id == 1)
                .First();
            Debug.WriteLine("Categoria" + c.ToString());


            return View();
        }

        public ActionResult CleanDB()
        {
            string s = Server.MapPath("~/Content/");
            InstallService install = new InstallService(s);

            install.DBClean();

            return View("Debug");
        }

        // GET: Test
        public ActionResult Init()
        {
            string s = Server.MapPath("~/Content/");
            InstallService install = new InstallService(s);

            install.DBClean();

            //DBexpander dbe = new DBexpander();
            //dbe.processFile(s+"csv/example.csv");

            install.DBLoadSample();

            return View();
        }

        public ActionResult Init2()
        {
            string s = Server.MapPath("~/Content/");
            InstallService install = new InstallService(s);

            //install.DBClean();

            //DBexpander dbe = new DBexpander();
            //dbe.processFile(s+"csv/example.csv");

            //install.DBLoadSample();
            install.UserDoLessons();

            return View("init");
        }

        // GET: Test
        public ActionResult Model()
        {
           
            //Lesson l = new Lesson(1, "Descricao", "A tua prima");
            //l.pollQuestions();

            //GlobalTest cg = new GlobalTest(1);
            //cg.pollQuestions();

            //CategoryLevel cl = new CategoryLevel(1, "a tua prima", 1, 0);
            //CategoryTest ct = cl.CreateCategoryTest();
            
            return View("Debug");
        }
        
        public ActionResult Home()
        {
            RocketEnglishv2.DAO.RocketEnglish a = new RocketEnglish();
            Utilizador u = a.Utilizador.First();

            RocketEnglishv2.Models.User user = new Models.User(u.id, u.nome, u.username, u.email, u.passsword, u.nivelGlobal, u.loginSeguidosMaximo, u.loginSeguidosAtual, u.dataUltimoLogin, u.tutorialFeito);

            HttpContext context = System.Web.HttpContext.Current;
            context.Session["user"] = user;

            return RedirectToAction("Index", "Home");
        }


        public ActionResult Video()
        {

            return View("Debug");
        }
        
        public ActionResult Image()
        {
            return View("Debug");
        }

        public ActionResult TestSave()
        {

            return View("Debug");
        }

        public ActionResult Translator()
        {
            String word = TranslatorContainer.TranslateBing("Bus", "en", "pt-pt");
            return View("Debug");
        }
    }
}

RocketEnglish/RocketEnglishv2/Views/Review/Global.cshtml
@using RocketEnglishv2.Models;
@model GlobalTest

@{
    CategoryLevel cl = ViewBag.CategoryLevel;
    List<Question> wrongQuestions = Model.getWrongQuestions();
    var nrWrongQuestions = wrongQuestions.Count;
    var nrQuestions = Model.questions.Count;
    var cena = "" + (nrQuestions - nrWrongQuestions);
}

<div class="container">
    <div id="post-lesson-wrapper" class="row">
        <div class="col-xs-2">
            <div id="lesson-result"></div>
        </div>
        <div class="col-xs-10" id="post-lesson-summary">
            <h1>Summary</h1>
            <h3 class="post-lesson-correct">Correct: @cena/@nrQuestions</h3>
            <h3 class="post-lesson-wrong">Wrong: @nrWrongQuestions/@nrQuestions</h3>
        </div>
        <div class="col-xs-12">
            <h2>Wrong Answers</h2>
            <ul class="post-lesson-questions">
            @foreach(Question q in wrongQuestions)
            {
                <li>
                    <span class="post-lesson-question">@q.Text</span>
                    <p class="post-lesson-answer">@q.Answer</p>
                </li>
            }
            </ul>
        </div>
        @Html.ActionLink("Exit", "Index", "Home", null,
                            new { @class = "btn btn-info" });
    </div>
</div>

@if (nrWrongQuestions <= 4)
{
    <audio autoplay hidden>
        <source src="~/Content/audio/levelup1.wav" type="audio/wav">
    </audio>
}
else
{
    <audio autoplay hidden>
        <source src="~/Content/audio/fail1.wav" type="audio/wav">
    </audio>
}


@{
    float jsResult = ((float)nrQuestions - (float)nrWrongQuestions) / ((float)nrQuestions);
}
<script src="~/Scripts/progressbar.min.js"></script>
<script>
    RocketEnglish.init.push(function () {
           var lvl = @Model.Level;           
    @if (nrWrongQuestions <= 4)
    {
        <text>
        RocketEnglish.SimpleInteraction("You leveled up! Your global level is now "+ lvl);
        makeHappy();
        greet();
        greet();
        </text>
    }
    else
    {
        <text>
        makeSad();
        </text>  
    }
    
    });

        $(document).ready(function(){
            var result = parseFloat('@jsResult.ToString().Replace(",", ".")');
            result = result.toFixed(2)
            var endColor;
            if(result >= 0.7)
                endColor = '#6FD57F';
            else if(result >= 0.5)
                endColor = '#F9A825';
            else
                endColor = '#D84315';

            var startColor = '#FC5B3F';


            var circle = new ProgressBar.Circle('#lesson-result', {
                color: '#455A64',
                strokeWidth: 5,
                trailWidth: 1,
                trailColor: '#eee',
                duration: 1500,
                text: {
                    value: '0'
                },
                step: function(state, bar) {
                    bar.setText((bar.value() * 100).toFixed(0));
                    bar.path.setAttribute('stroke', state.color);
                }
            });

            circle.animate(result, {
                from: {color: startColor},
                to: {color: endColor}
            }, function() {
                $('#lesson-result p.progressbar-text').css('color', endColor);
            });
        });
</script>

RocketEnglish/RocketEnglishv2/Views/Review/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

RocketEnglish/RocketEnglishv2/Views/Review/Lesson.cshtml
@using RocketEnglishv2.Models;
@model Lesson
@{
    CategoryLevel cl = ViewBag.CategoryLevel;
    List<Question> wrongQuestions = Model.getWrongQuestions();
    var nrWrongQuestions = wrongQuestions.Count;
    var nrQuestions = Model.questions.Count;
    var cena = "" + (nrQuestions - nrWrongQuestions);
}

<div class="container">
    <div id="post-lesson-wrapper" class="row">
        <div class="col-xs-2">
            <div id="lesson-result"></div>
        </div>
        <div class="col-xs-10" id="post-lesson-summary">
            <h1>Summary</h1>
            <h3 class="post-lesson-correct">Correct: @cena/@nrQuestions</h3>
            <h3 class="post-lesson-wrong">Wrong: @nrWrongQuestions/@nrQuestions</h3>
        </div>
        <div class="col-xs-12">
            <h2>Wrong Answers</h2>
            <ul class="post-lesson-questions">
            @foreach(Question q in wrongQuestions)
            {
                <li>
                    <span class="post-lesson-question">@q.Text</span>
                    <p class="post-lesson-answer">@q.Answer</p>
                </li>
            }
            </ul>
        </div>
        <div style="margin: 0 auto">
            <center>
        @Html.ActionLink("Retry", "Lesson", "Introduction", new { id = cl.Level, idLesson = Model.Id, idCategory = cl.CategoryId },
                                                                        new { @class = "btn btn-danger" })
        @Html.ActionLink("Exit", "Index", "Home", null, new { @class = "btn btn-primary" })
                </center>
        </div>
    </div>
</div>

@{
    float jsResult = ((float)nrQuestions - (float)nrWrongQuestions) / ((float)nrQuestions);
}

@if(nrWrongQuestions < 4)
{
            <audio autoplay hidden>
                <source src="~/Content/audio/levelup1.wav" type="audio/wav">
            </audio>
}
else
{
            <audio autoplay hidden>
                <source src="~/Content/audio/fail1.wav" type="audio/wav">
            </audio>
}

    <script src="~/Scripts/progressbar.min.js"></script>
<script>
    RocketEnglish.init.push(function () {
                          
        @if (nrWrongQuestions < 4)
    {
        <text>
        makeHappy();
        greet();
        greet();
        </text>
    }
    else
    {
        <text>
        makeSad();
        </text>  
    }
    
    });

        $(document).ready(function(){
            var result = parseFloat('@jsResult.ToString().Replace(",", ".")');
            result = result.toFixed(2)
            var endColor;
            if(result >= 0.7)
                endColor = '#6FD57F';
            else if(result >= 0.5)
                endColor = '#F9A825';
            else
                endColor = '#D84315';

            var startColor = '#FC5B3F';


            var circle = new ProgressBar.Circle('#lesson-result', {
                color: '#455A64',
                strokeWidth: 5,
                trailWidth: 1,
                trailColor: '#eee',
                duration: 1500,
                text: {
                    value: '0'
                },
                step: function(state, bar) {
                    bar.setText((bar.value() * 100).toFixed(0));
                    bar.path.setAttribute('stroke', state.color);
                }
            });

            circle.animate(result, {
                from: {color: startColor},
                to: {color: endColor}
            }, function() {
                $('#lesson-result p.progressbar-text').css('color', endColor);
            });
        });
        </script>

RocketEnglish/RocketEnglishv2/Views/Review/Test.cshtml
@using RocketEnglishv2.Models;
@model CategoryTest

@{
    CategoryLevel cl = ViewBag.CategoryLevel;
    List<Question> wrongQuestions = Model.getWrongQuestions();
    var nrWrongQuestions = wrongQuestions.Count;
    var nrQuestions = Model.questions.Count;
    var cena = "" + (nrQuestions - nrWrongQuestions);
}

<div class="container">
    <div id="post-lesson-wrapper" class="row">
        <div class="col-xs-2">
            <div id="lesson-result"></div>
        </div>
        <div class="col-xs-10" id="post-lesson-summary">
            <h1>Summary</h1>
            <h3 class="post-lesson-correct">Correct: @cena/@nrQuestions</h3>
            <h3 class="post-lesson-wrong">Wrong: @nrWrongQuestions/@nrQuestions</h3>
        </div>
        <div class="col-xs-12">
            <h2>Wrong Answers</h2>
            <ul class="post-lesson-questions">
            @foreach(Question q in wrongQuestions)
            {
                <li>
                    <span class="post-lesson-question">@q.Text</span>
                    <p class="post-lesson-answer">@q.Answer</p>
                </li>
            }
            </ul>
        </div>
        @Html.ActionLink("Exit", "Index", "Home", null,new { @class = "btn btn-primary" })
    </div>
</div>
@{
    float jsResult = ((float)nrQuestions - (float)nrWrongQuestions) / ((float)nrQuestions);
}
@if (nrWrongQuestions < 4)
{
    <audio autoplay hidden>
        <source src="~/Content/audio/levelup1.wav" type="audio/wav">
    </audio>
}
else
{
    <audio autoplay hidden>
        <source src="~/Content/audio/fail1.wav" type="audio/wav">
    </audio>
}

<script src="~/Scripts/progressbar.min.js"></script>
<script>
    RocketEnglish.init.push(function () {
                          
@if (nrWrongQuestions < 4)
{
    <text>
    makeHappy();
    greet();
    greet();
    </text>
}
else
{
    <text>
    makeSad();
    </text>  
}
    
    });

        $(document).ready(function(){
            var result = parseFloat('@jsResult.ToString().Replace(",", ".")');
            result = result.toFixed(2)
            var endColor;
            if(result >= 0.7)
                endColor = '#6FD57F';
            else if(result >= 0.5)
                endColor = '#F9A825';
            else
                endColor = '#D84315';

            var startColor = '#FC5B3F';


            var circle = new ProgressBar.Circle('#lesson-result', {
                color: '#455A64',
                strokeWidth: 5,
                trailWidth: 1,
                trailColor: '#eee',
                duration: 1500,
                text: {
                    value: '0'
                },
                step: function(state, bar) {
                    bar.setText((bar.value() * 100).toFixed(0));
                    bar.path.setAttribute('stroke', state.color);
                }
            });

            circle.animate(result, {
                from: {color: startColor},
                to: {color: endColor}
            }, function() {
                $('#lesson-result p.progressbar-text').css('color', endColor);
            });
        });
</script>